import type { DesignVersion, Project, ProjectAiUsage } from "@silicon-canvas/shared/contracts";
import { useState } from "react";
import type { FpgaExport } from "../../api/client";
import "./ProjectPanel.css";

type ProjectPanelProps = { project: Project | null; versions: DesignVersion[]; usage: ProjectAiUsage | null; exportResult: FpgaExport | null; busy: boolean; onRestore: (versionId: string) => void; onExport: (board: string) => void };

export function ProjectPanel({ project, versions, usage, exportResult, busy, onRestore, onExport }: ProjectPanelProps) {
  const [board, setBoard] = useState("icestick");
  if (!project) return <section className="project-panel project-placeholder"><p className="section-kicker">PROJECT CONTROLS</p><h2>Create a design to inspect its history</h2><p>Version restore, token usage, and board export become available after the first generated project.</p></section>;
  const tokenSummary = usage?.summary;
  return <section className="project-panel"><header><div><p className="section-kicker">PROJECT CONTROLS</p><h2>{project.name}</h2><p>{project.prompt}</p></div><span>{project.status}</span></header><div className="project-grid"><section><div className="project-section-heading"><div><h3>Version history</h3><p>Every generate, restore, and repair creates a new immutable version.</p></div><b>{versions.length} saved</b></div><div className="version-list">{versions.map((version) => <article key={version.id} className={version.id === project.activeVersionId ? "active" : ""}><div><strong>v{version.number}</strong><span>{version.id === project.activeVersionId ? "Active" : version.generationStatus}</span><p>{version.sourcePrompt}</p></div><button className="button-secondary" type="button" onClick={() => onRestore(version.id)} disabled={busy || version.id === project.activeVersionId}>{version.id === project.activeVersionId ? "Current" : "Restore"}</button></article>)}</div></section><section><div className="project-section-heading"><div><h3>AI token usage</h3><p>Provider-reported counts for this project only.</p></div></div>{tokenSummary ? <div className="usage-summary"><article><span>Requests</span><b>{tokenSummary.requestCount}</b></article><article><span>Input</span><b>{tokenSummary.inputTokens.toLocaleString()}</b></article><article><span>Output</span><b>{tokenSummary.outputTokens.toLocaleString()}</b></article><article><span>Total</span><b>{tokenSummary.totalTokens.toLocaleString()}</b></article></div> : <p className="project-note">Loading AI usage…</p>}<div className="export-card"><div><h3>FPGA package</h3><p>Create constraints, build script, and handoff notes for a supported board.</p></div><select value={board} onChange={(event) => setBoard(event.target.value)} aria-label="FPGA board"><option value="icestick">iCEstick</option><option value="icebreaker">iCEbreaker</option><option value="arty_a7">Arty A7</option></select><button className="button-primary" type="button" onClick={() => onExport(board)} disabled={busy || !project.activeVersionId}>Export FPGA files</button>{exportResult && <p className="export-result">Ready: {exportResult.artifacts.map((artifact) => artifact.path).join(", ")}</p>}</div></section></div></section>;
}
